import { useEffect, useState } from 'react';

type Stats = { totalPrinters:number; printersWithVerifiedCompatibility:number; totalUniqueOemCartridges:number; totalVerifiedRelationships:number };
type Manufacturer = { id:number; name:string; printer_count:number };
type Printer = { id:number; manufacturer:string; model_name:string; has_replaceable_cartridges:number; verified_cartridge_count:number; cartridge_count:number };
type Cartridge = { id:number; part_number:string; kind:string; color:string|null; yield_pages:number|null; verification_status:string; region:string; source_url:string; verified_at:string|null };
type PrinterDetail = Printer & { sources:Array<{name:string;source_url:string;verification_status:string;region:string}>; cartridges:Cartridge[] };

export function App() {
  const [stats,setStats]=useState<Stats|null>(null), [manufacturers,setManufacturers]=useState<Manufacturer[]>([]), [printers,setPrinters]=useState<Printer[]>([]);
  const [selected,setSelected]=useState<PrinterDetail|null>(null), [query,setQuery]=useState(''), [manufacturer,setManufacturer]=useState(''), [loading,setLoading]=useState(true), [error,setError]=useState('');
  useEffect(()=>{Promise.all([get<Stats>('/api/stats'),get<Manufacturer[]>('/api/manufacturers')]).then(([s,m])=>{setStats(s);setManufacturers(m)}).catch((e:Error)=>setError(e.message))},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>{setLoading(true);const p=new URLSearchParams({limit:'60'});if(query.trim())p.set('q',query.trim());if(manufacturer)p.set('manufacturer',manufacturer);get<Printer[]>(`/api/printers?${p}`).then(setPrinters).catch((e:Error)=>setError(e.message)).finally(()=>setLoading(false))},180);return()=>clearTimeout(timer)},[query,manufacturer]);
  const openPrinter=(id:number)=>get<PrinterDetail>(`/api/printers/${id}`).then(setSelected).catch((e:Error)=>setError(e.message));
  return <main>
    <header className="hero"><div className="brand"><span className="brand-mark">PC</span><span>Printcartridge DB</span></div><div className="hero-copy"><p className="eyebrow">European OEM compatibility index</p><h1>Find the right cartridge.<br/><em>Trust the evidence.</em></h1><p className="lede">Search printer models and inspect genuine ink and toner relationships backed by official manufacturer sources.</p></div>
      {stats&&<section className="stats"><Stat value={stats.totalPrinters} label="printer models"/><Stat value={stats.totalUniqueOemCartridges} label="verified cartridges"/><Stat value={stats.totalVerifiedRelationships} label="verified matches"/><Stat value={stats.printersWithVerifiedCompatibility} label="covered printers"/></section>}</header>
    <section className="workspace"><div className="search-panel"><label className="search"><span>Search the catalog</span><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try ECOSYS, VersaLink, HL-2070N…"/></label><label className="filter"><span>Manufacturer</span><select value={manufacturer} onChange={e=>setManufacturer(e.target.value)}><option value="">All manufacturers</option>{manufacturers.map(m=><option key={m.id} value={m.name}>{m.name} · {m.printer_count}</option>)}</select></label></div>
      {error&&<p className="error">{error}</p>}<div className="result-meta"><strong>{loading?'Searching…':`${printers.length} models shown`}</strong><span>Verified data is marked in green</span></div><div className="layout"><section className="results" aria-label="Printer results">
        {!loading&&printers.map(p=><button className={`printer-row ${selected?.id===p.id?'active':''}`} key={p.id} onClick={()=>openPrinter(p.id)}><span className="printer-icon">{p.manufacturer[0]}</span><span className="printer-title"><small>{p.manufacturer}</small><strong>{p.model_name}</strong></span><span className={p.verified_cartridge_count?'pill verified':'pill'}>{p.verified_cartridge_count?`${p.verified_cartridge_count} verified`:'catalog only'}</span><span className="arrow">›</span></button>)}
        {!loading&&!printers.length&&<div className="empty"><strong>No matching models</strong><span>Try a shorter model number or another manufacturer.</span></div>}</section><aside className={`detail ${selected?'open':''}`}>{selected?<PrinterCard printer={selected} onClose={()=>setSelected(null)}/>:<div className="detail-placeholder"><span className="large-mark">OEM</span><h2>Select a printer</h2><p>Compatibility, cartridge details, region, and official evidence will appear here.</p></div>}</aside></div></section>
    <footer><span>Only genuine OEM ink and toner</span><span>Europe · Spain prioritized</span><span>Sources retained per relationship</span></footer></main>;
}

function PrinterCard({printer,onClose}:{printer:PrinterDetail;onClose:()=>void}) {return <div><button className="close" onClick={onClose} aria-label="Close">×</button><p className="eyebrow">{printer.manufacturer}</p><h2>{printer.model_name}</h2><div className="detail-status"><span className={printer.cartridges.some(c=>c.verification_status==='verified')?'dot good':'dot'}/>{printer.cartridges.length?`${printer.cartridges.length} OEM records`:'No cartridge compatibility recorded'}</div><h3>Compatible cartridges</h3><div className="cartridges">{printer.cartridges.map((c,i)=><article className="cartridge" key={`${c.id}-${c.region}-${i}`}><div className="cartridge-top"><strong>{c.part_number}</strong><span className={`pill ${c.verification_status==='verified'?'verified':''}`}>{c.verification_status}</span></div><p>{c.kind.toUpperCase()} · {c.color||'color not stated'}{c.yield_pages?` · ${c.yield_pages.toLocaleString()} pages`:''}</p><div className="evidence"><span>{c.region}</span>{c.verified_at&&<span>Checked {new Date(c.verified_at).toLocaleDateString()}</span>}<a href={c.source_url} target="_blank" rel="noreferrer">Official source ↗</a></div></article>)}</div>{!printer.cartridges.length&&<div className="empty compact"><strong>Catalog record only</strong><span>No compatibility is inferred from the model name.</span></div>}{!!printer.sources.length&&<><h3>Printer sources</h3>{printer.sources.map((s,i)=><a className="source-link" href={s.source_url} target="_blank" rel="noreferrer" key={`${s.source_url}-${i}`}>{s.name}<span>{s.region} · {s.verification_status} ↗</span></a>)}</>}</div>}
function Stat({value,label}:{value:number;label:string}){return <div><strong>{value.toLocaleString()}</strong><span>{label}</span></div>}
async function get<T>(url:string):Promise<T>{const response=await fetch(url);if(!response.ok)throw new Error(`Request failed: ${response.status}`);return response.json() as Promise<T>}
