import { useEffect, useState } from 'react';

type Stats = { totalPrinters:number; printersWithVerifiedCompatibility:number; totalUniqueOemCartridges:number; totalVerifiedRelationships:number };
type Manufacturer = { id:number; name:string; printer_count:number };
type Printer = { id:number; manufacturer:string; model_name:string; has_replaceable_cartridges:number; verified_cartridge_count:number; cartridge_count:number };
type PrinterPage = { items:Printer[]; total:number; page:number; pageSize:number; totalPages:number };
type Cartridge = { id:number; part_number:string; kind:string; color:string|null; yield_pages:number|null; verification_status:string; region:string; source_url:string; verified_at:string|null };
type PrinterDetail = Printer & { sources:Array<{name:string;source_url:string;verification_status:string;region:string}>; cartridges:Cartridge[] };
type Collector = { id:string; name:string; description:string; status:'idle'|'running'|'succeeded'|'failed'|'stopped'; log:string; output:string; outputExists:boolean; startedAt?:string; finishedAt?:string };

export function App() {
  const [stats,setStats]=useState<Stats|null>(null), [manufacturers,setManufacturers]=useState<Manufacturer[]>([]), [printers,setPrinters]=useState<Printer[]>([]);
  const [selected,setSelected]=useState<PrinterDetail|null>(null), [query,setQuery]=useState(''), [manufacturer,setManufacturer]=useState(''), [page,setPage]=useState(1), [total,setTotal]=useState(0), [totalPages,setTotalPages]=useState(1), [loading,setLoading]=useState(true), [error,setError]=useState('');
  useEffect(()=>{Promise.all([get<Stats>('/api/stats'),get<Manufacturer[]>('/api/manufacturers')]).then(([s,m])=>{setStats(s);setManufacturers(m)}).catch((e:Error)=>setError(e.message))},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>{setLoading(true);const p=new URLSearchParams({page:String(page),pageSize:'10'});if(query.trim())p.set('q',query.trim());if(manufacturer)p.set('manufacturer',manufacturer);get<PrinterPage>(`/api/printers?${p}`).then(result=>{setPrinters(result.items);setTotal(result.total);setTotalPages(result.totalPages);if(result.page!==page)setPage(result.page)}).catch((e:Error)=>setError(e.message)).finally(()=>setLoading(false))},180);return()=>clearTimeout(timer)},[query,manufacturer,page]);
  const openPrinter=(id:number)=>get<PrinterDetail>(`/api/printers/${id}`).then(setSelected).catch((e:Error)=>setError(e.message));
  return <main>
    <header className="hero"><div className="brand"><span className="brand-mark">PC</span><span>Printcartridge DB</span></div><div className="hero-copy"><p className="eyebrow">European OEM compatibility index</p><h1>Find the right cartridge.<br/><em>Trust the evidence.</em></h1><p className="lede">Search printer models and inspect genuine ink and toner relationships backed by official manufacturer sources.</p></div>
      {stats&&<section className="stats"><Stat value={stats.totalPrinters} label="printer models"/><Stat value={stats.totalUniqueOemCartridges} label="verified cartridges"/><Stat value={stats.totalVerifiedRelationships} label="verified matches"/><Stat value={stats.printersWithVerifiedCompatibility} label="covered printers"/></section>}</header>
    <section className="workspace"><div className="search-panel"><label className="search"><span>Search the catalog</span><input autoFocus value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Try ECOSYS, VersaLink, HL-2070N…"/></label><label className="filter"><span>Manufacturer</span><select value={manufacturer} onChange={e=>{setManufacturer(e.target.value);setPage(1)}}><option value="">All manufacturers</option>{manufacturers.map(m=><option key={m.id} value={m.name}>{m.name} · {m.printer_count}</option>)}</select></label></div>
      {error&&<p className="error">{error}</p>}<div className="result-meta"><strong>{loading?'Searching…':`${total} models · page ${page} of ${totalPages}`}</strong><span>Verified data is marked in green</span></div><div className="layout"><section><div className="results" aria-label="Printer results">
        {!loading&&printers.map(p=><button className={`printer-row ${selected?.id===p.id?'active':''}`} key={p.id} onClick={()=>openPrinter(p.id)}><span className="printer-icon">{p.manufacturer[0]}</span><span className="printer-title"><small>{p.manufacturer}</small><strong>{p.model_name}</strong></span><span className={p.verified_cartridge_count?'pill verified':'pill'}>{p.verified_cartridge_count?`${p.verified_cartridge_count} verified`:'catalog only'}</span><span className="arrow">›</span></button>)}
        {!loading&&!printers.length&&<div className="empty"><strong>No matching models</strong><span>Try a shorter model number or another manufacturer.</span></div>}</div>{!loading&&totalPages>1&&<Pagination page={page} totalPages={totalPages} onChange={next=>{setPage(next);setSelected(null)}}/>}</section><aside className={`detail ${selected?'open':''}`}>{selected?<PrinterCard printer={selected} onClose={()=>setSelected(null)}/>:<div className="detail-placeholder"><span className="large-mark">OEM</span><h2>Select a printer</h2><p>Compatibility, cartridge details, region, and official evidence will appear here.</p></div>}</aside></div></section>
    <CollectorPanel onImported={()=>get<Stats>('/api/stats').then(setStats)}/><footer><span>Only genuine OEM ink and toner</span><span>Europe · Spain prioritized</span><span>Sources retained per relationship</span></footer></main>;
}

function PrinterCard({printer,onClose}:{printer:PrinterDetail;onClose:()=>void}) {return <div><button className="close" onClick={onClose} aria-label="Close">×</button><p className="eyebrow">{printer.manufacturer}</p><h2>{printer.model_name}</h2><div className="detail-status"><span className={printer.cartridges.some(c=>c.verification_status==='verified')?'dot good':'dot'}/>{printer.cartridges.length?`${printer.cartridges.length} OEM records`:'No cartridge compatibility recorded'}</div><h3>Compatible cartridges</h3><div className="cartridges">{printer.cartridges.map((c,i)=><article className="cartridge" key={`${c.id}-${c.region}-${i}`}><div className="cartridge-top"><strong>{c.part_number}</strong><span className={`pill ${c.verification_status==='verified'?'verified':''}`}>{c.verification_status}</span></div><p>{c.kind.toUpperCase()} · {c.color||'color not stated'}{c.yield_pages?` · ${c.yield_pages.toLocaleString()} pages`:''}</p><div className="evidence"><span>{c.region}</span>{c.verified_at&&<span>Checked {new Date(c.verified_at).toLocaleDateString()}</span>}<a href={c.source_url} target="_blank" rel="noreferrer">Official source ↗</a></div></article>)}</div>{!printer.cartridges.length&&<div className="empty compact"><strong>Catalog record only</strong><span>No compatibility is inferred from the model name.</span></div>}{!!printer.sources.length&&<><h3>Printer sources</h3>{printer.sources.map((s,i)=><a className="source-link" href={s.source_url} target="_blank" rel="noreferrer" key={`${s.source_url}-${i}`}>{s.name}<span>{s.region} · {s.verification_status} ↗</span></a>)}</>}</div>}
function Stat({value,label}:{value:number;label:string}){return <div><strong>{value.toLocaleString()}</strong><span>{label}</span></div>}
function Pagination({page,totalPages,onChange}:{page:number;totalPages:number;onChange:(page:number)=>void}){const pages=pageNumbers(page,totalPages);return <nav className="pagination" aria-label="Printer pages"><button disabled={page===1} onClick={()=>onChange(page-1)}>←</button>{pages.map((item,index)=>item==='…'?<span key={`gap-${index}`}>…</span>:<button key={item} className={item===page?'current':''} aria-current={item===page?'page':undefined} onClick={()=>onChange(item as number)}>{item}</button>)}<button disabled={page===totalPages} onClick={()=>onChange(page+1)}>→</button></nav>}
function pageNumbers(page:number,total:number):(number|'…')[]{if(total<=7)return Array.from({length:total},(_,i)=>i+1);if(page<=4)return [1,2,3,4,5,'…',total];if(page>=total-3)return [1,'…',total-4,total-3,total-2,total-1,total];return [1,'…',page-1,page,page+1,'…',total]}
async function get<T>(url:string):Promise<T>{const response=await fetch(url);if(!response.ok)throw new Error(`Request failed: ${response.status}`);return response.json() as Promise<T>}
async function post<T>(url:string):Promise<T>{const response=await fetch(url,{method:'POST'});const body=await response.json() as T&{error?:string};if(!response.ok)throw new Error(body.error||`Request failed: ${response.status}`);return body}

function CollectorPanel({onImported}:{onImported:()=>void}) {
  const [collectors,setCollectors]=useState<Collector[]>([]), [message,setMessage]=useState(''), [busy,setBusy]=useState('');
  const refresh=()=>get<Collector[]>('/api/collectors').then(setCollectors).catch((error:Error)=>setMessage(error.message));
  useEffect(()=>{refresh();const timer=window.setInterval(()=>{if(collectors.some(item=>item.status==='running'))refresh()},1500);return()=>clearInterval(timer)},[collectors]);
  const action=async(id:string,type:'run'|'import')=>{setBusy(`${id}-${type}`);setMessage('');try{const result=await post<Record<string,unknown>>(`/api/collectors/${id}/${type}`);setMessage(type==='run'?`${id}: collection started`:`${id}: import completed — ${JSON.stringify(result)}`);if(type==='import')onImported();await refresh()}catch(error){setMessage(error instanceof Error?error.message:String(error))}finally{setBusy('')}};
  const running=collectors.some(item=>item.status==='running');
  return <section className="collector-panel"><div className="collector-heading"><div><p className="eyebrow">Local data operations</p><h2>Collectors & imports</h2><p>Collection uses only the existing official-source adapters, rate limits, robots rules, retries, and saved checkpoints. Review the log before importing.</p></div><span className="local-badge">localhost only</span></div>{message&&<p className="operation-message">{message}</p>}<div className="collector-grid">{collectors.map(item=><article className="collector-card" key={item.id}><div className="collector-title"><div><small>{item.id}</small><h3>{item.name}</h3></div><span className={`collector-status ${item.status}`}>{item.status}</span></div><p>{item.description}</p><div className="collector-file"><span>{item.outputExists?'Output ready':'No output yet'}</span><code>{item.output}</code></div><div className="collector-actions">{item.id!=='brother'&&<button disabled={running||!!busy} onClick={()=>action(item.id,'run')}>{busy===`${item.id}-run`?'Starting…':'Collect'}</button>}<button className="secondary" disabled={running||!item.outputExists||!!busy} onClick={()=>action(item.id,'import')}>{busy===`${item.id}-import`?'Importing…':'Import to MVP'}</button></div>{item.log&&<details open={item.status==='failed'}><summary>Collector log</summary><pre>{item.log}</pre></details>}</article>)}</div></section>;
}
